### PR TITLE
Add docker image to run googler with docker

### PR DESCRIPTION
**Pull request by bobey**
This PR adds a Dockerfile to build tiny lightweight docker image in order to run `googler` with ease.

### CODE REVIEW

**Comment by jarun** [comment]
Hi,

Please help me understand this PR.

`googler` is a standalone file (if you have Pyhton 3.3+ installed) without any apparent intention or capabilities to harm a system. Why would anyone want to run it in an isolated environment?

**Comment by bobey** [comment]
Hi,

Of course, `googler` is a standalone file without any apparent intention or capabilities to harm a system.
But I'm pretty sure having the option to run `googler` without worrying about Python should interest a number of people. You may wanna run it on a cloud provider interpreting Docker images for example as Zeit do with `now` command (https://zeit.co/now#whats-now).

**Comment by jarun** [comment]
OK. I'll wait for inputs from @zmwangx too.

**Comment by bobey** [comment]
No problem. If you don't feel comfortable to merge that into your repository, I can let it leave in my own dedicated repository and push the image on Docker hub.

**Comment by jarun** [comment]
> If you don't feel comfortable

Nothing like that! Just want to have my collaborator in sync and get his opinion.

**Comment by zmwangx** [comment]
I won't judge you for wanting to run a single Python script with Docker (though I find it amusing), but this doesn't belong to the repo. I mean, just look around, I've yet to see a comparable project to include a Dockerfile. It's also rather trivial for anyone who knows Docker to put one together.

**Comment by jarun** [comment]
googler needs just the Python base, no additional requirements or extra packages. We have taken great care to keep it that way. Installing Python on docker (or anywhere for that matter) should be pretty standard. So I'ld skip this and probably point at our repo for reference if someone approaches with a Docker requirement.

Closing the PR.

**Pull request closed without merging**
