### PR TITLE
googler: Use single quotes consistently

### PR DESCRIPTION
**Pull request by zmwangx**
Replace double quotes with single quotes.

See https://github.com/jarun/googler/pull/92#issuecomment-221184312 and https://github.com/jarun/googler/pull/92#issuecomment-221194202.

Let's try to consistently use single quotes in the future so that there's no need to choose, especially for new contributors (if any) who want to follow existing styles.

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
I guess we introduced an issue: https://travis-ci.org/jarun/googler/jobs/132489980

**Comment by zmwangx** [comment]
Probably not in this commit, because nothing in `GoogleParser` was changed. But we'll see.

**Comment by zmwangx** [comment]
I think it is just malformed HTML. In the HTML response, there are 444 open <div> tags and 445 close </div> tags. I haven't located where exactly is wrong yet.

**Comment by zmwangx** [comment]
#94

**Pull request merged**
