### PR TITLE
Include Python version in debug output

### PR DESCRIPTION
**Pull request by zmwangx**
Why ask for it when we can extract that ourselves.

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by zmwangx** [comment]
@jarun Absolutely no offense, but are you able to see my comments in the thread https://github.com/zmwangx/googler/commit/e3f52f19b77303fd01b9e45690b990c6e5fc4903#commitcomment-23617093? Judging from your comments I feel like my comments are somehow hidden from you...

**Comment by jarun** [comment]
Now I can see. The page wasn't auto-updating.

**Comment by zmwangx** [comment]
Oh yeah, I had to refresh the page constantly too. I do have email notifications on, though.

**Comment by jarun** [comment]
My mailbox isn't open...

**Pull request merged**
