### PR TITLE
Add option --immediately (-i) to open first page and exit

### PR DESCRIPTION
**Pull request by RatanRSur**
I went ahead and added the feature I mentioned in my issue since it was clear from the plethora of behaviors that already existed that there would be an easy place to hook this in.

### CODE REVIEW

**Comment by jarun** [comment]
Please have your own fork for this. `googler` development is almost frozen.

**Comment by jarun** [comment]
He also wants to open the links in the browser.

I think one can take the json output from `googler --np`, cherry pick the URLs and open all of them in the browser.

**Comment by kenorb** [comment]
If you use [Hyper terminal](https://hyper.is/), it highlights links automatically, so you can click on them.

Also, to search in the terminal then open in the browser, you can also try: https://duckduckgo.com/tty/ (it's cool).

**Comment by jarun** [comment]
> Also, to search in the terminal then open in another tab, you can also try: https://duckduckgo.com/tty/ (it's cool).

and there's [ddgr](https://github.com/jarun/ddgr).

Anyway, there's a one-liner command to replace this PR (on bash):

    BROWSER=firefox googler -j hello

**Pull request closed without merging**
