### PR TITLE
googler: Allow browser output in certain cases

### LINKED ISSUE #125: Unable to integrate with text-based browsers
Due to redirecting stdin and stderr unconditionally to `/dev/null`in https://github.com/jarun/googler/blob/dfc988f16c7e17bb691b3ef4e154f17ae5436588/googler#L93-L109 (which IIRC is there to suppress logging of graphical browsers), currently googler can't integrate with text-based browsers like `w3m`:

```
BROWSER=w3m googler -n 3 -d google
[DEBUG] Version 2.6
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&num=3&oe=UTF-8&q=google&start=0
[DEBUG] Cookie: NID=85=0ZPk4CbfrgeZk1YH8HkP5ETEVlEPA8Iah5wr63Nb2LJKRDITbPjbH14B1RksRJDiUOvil3RjWUDEOySNarkAKuVQqMY3kop27vLgHbpAdjrY6IIhZZvsq4m5tjbQW_MUx6wmQE2v0O8B1g
[DEBUG] Response body written to '/tmp/googler-response-nb04dlxs'.

1 Google
https://www.google.com/
Search the world's information, including webpages, images, videos and more. Google has many special features to help
you find exactly what you're looking ...

2 Google Maps
https://maps.google.com/
Find local businesses, view maps and get driving directions in Google Maps.

3 Google (@google) | Twitter
https://twitter.com/google?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

googler (? for help) 1
[DEBUG] Opening https://www.google.com/
googler (? for help) q
```

(Nothing else appears after `[DEBUG] Opening https://www.google.com/`.)

## Proposed solution

Add a `--disable-browser-output` option to only redirect browser stdin and stdout to `/dev/null` when the option is on; or add a `--enable-browser-output` option, which is the other way round.

## Temporary workaround

Until this is resolved, if you want to integrate with a text-based browser, you can apply this patch (assuming your googler is up-to-date with the master branch): https://gist.githubusercontent.com/zmwangx/d250bd0521b96cec2b21a1bc2db57a6b/raw/575b5af324e6e3b323a90da2ba1c76e725d76151/googler.patch (https://git.io/v6N80):

```sh
$ cd /directory/where/googler/lives
$ curl -sSL https://git.io/v6N80 | patch -p1
```

By the way, the easiest way to be up-to-date with the master branch, assuming you're using a recent enough version with self-upgrade support, is

```
$ googler -U --include-git
```

### PR DESCRIPTION
**Pull request by zmwangx**
Cases:

- `BROWSER` is one of the known text-based browsers: currently `elinks`, `links`, `lynx` and `w3m`.

- User explicitly passes the `--enable-browser-output` option.

Fixes #125.

## Note

This is a preview, not to be merged yet. Code is done, but I still need to do docs and shell completion. I'll finish the docs later today when I have time.

### CODE REVIEW

**Comment by zmwangx** [comment]
Kind of an embarrassing bug because README says

> You can integrate it with a text-based browser.

**Comment by zmwangx** [comment]
@jarun Done updating docs and completion. Added a new FAQ section in README. Since I added quite a bit of docs, please proofread.

Also, I moved all headings one level down in README, because as I said in the commit message,

> We've been using `<h1>` for the section titles, which doesn't make sense logically, and they look scarily big with GitHub's current stylesheet, too.

**Comment by zmwangx** [comment]
Also, a slight reminder: what about releasing a new version after this is merged?

**Comment by jarun** [comment]
Merged. I can do it tomorrow.
Can you think of some new features we can add?

**Comment by zmwangx** [comment]
Thought of one low hanging fruit: #128. Other than that I can't think of anything that is close to trivial to implement.

**Comment by jarun** [comment]
Merged that. Yes, me neither. I think we are quite feature-saturated here.

**Comment by zmwangx** [comment]
Yeah, let's just show them what we have in store.

**Comment by jarun** [comment]
:+1:

**Pull request merged**
