### PR TITLE
Fixed repl.it command

### PR DESCRIPTION
**Pull request by PDanielY**
@Mosrod did the thing wrong. So I fixed it 👍 

> Also not trying to sound mean or anything

### CODE REVIEW

**Comment by jarun** [comment]
Can you fix pdd as well? https://github.com/jarun/pdd

**Comment by PDanielY** [comment]
I'll try

**Comment by PDanielY** [comment]
The repl works fine. Did someone say that couldn't run it?

**Comment by jarun** [comment]
OK. So `chmod` does the trick. Thanks!

**Pull request merged**
