### PR TITLE
Add --unfilter flag, make implicit on --noprompt

### PR DESCRIPTION
**Pull request by michaelhood**

### CODE REVIEW

**Comment by zmwangx** [comment]
I reserve my opinion on whether this option is a good idea. But making this implicit on `--noprompt` is simply bad. In most cases it only serves to dilute useful results.

**Comment by jarun** [comment]
Have the `--unfilter` flag if you must, but please decouple it from `--noprompt`.

**Comment by michaelhood** [comment]
Fair points! Will refactor and reopen ASAP.

**Comment by jarun** [comment]
You didn't really have to close the PR. You can update an existing PR.

**Pull request closed without merging**
