### PR TITLE
Automated test script and Travis CI integration

### PR DESCRIPTION
**Pull request by zmwangx**
Just to give you something to review. The automated test script is hopefully both reasonably robust and user friendly. Give it a spin:

    ./test

or

    ./test -q

which is quieter. Or read the brief help text first (./test -h).

Some initial builds on my fork can be found here: https://travis-ci.org/zmwangx/googler/builds. Unfortunately I spammed thousands of queries in the first build, and was subsequently blocked. (Although I've updated the script to only generate 100 — this number is customizable — queries.) There seems to be nothing I could do except to wait it out.

### CODE REVIEW

**Comment by jarun** [comment]
All clear! (as far as I checked)

**Comment by zmwangx** [comment]
Oops, I had a fixup commit right there which I thought I'd rebase after some discussions... I should have added a [WIP]. Would you mind if I rebase and force push to master? Not the best idea, but better than having a fixup commit that was meant to be rebased to begin with.

**Comment by zmwangx** [comment]
Also, could you please set up https://travis-ci.org/jarun/googler?

**Comment by zmwangx** [comment]
I've since pushed another (477af54) fix to this branch, an issue I discovered when I was reading the help I wrote myself. I probably need to read through the test script once more, because I wrote it at 2AM last night :wink:

**Comment by zmwangx** [comment]
And holy cow, the latest fixup commit (I forgot `[ci skip]` apparently) is all green on Travis! https://travis-ci.org/zmwangx/googler/builds/111285850.

**Comment by zmwangx** [comment]
I have moved the discussion to a new PR #32. The comment above is not true: I made a newbie mistake of modifying global variable in a pipe, which resulted in update to `exitcode` not being reflected.

**Comment by jarun** [comment]
https://travis-ci.org/jarun/googler ready.

**Pull request merged**
