### PR TITLE
Revert "Include commit hash in version number when possible"

### PR DESCRIPTION
**Pull request by jarun**
Reverts jarun/googler#171

### CODE REVIEW

**Comment by zmwangx** [comment]
Need to apply 6a3c025 independently.

**Comment by jarun** [comment]
Yes please push directly. I do a squash merge nowadays. Probably remove the merge and reversal from the version history as well.

**Comment by zmwangx** [comment]
> I do a squash merge nowadays.

Oh.

That's probably not a good idea for multi-commits PRs (unless the commits need squashing). Squashing unrelated commits makes bisecting a lot harder.

**Comment by zmwangx** [comment]
Pushed 7758cf786119f4fc3298475b4fa9069ca1fc8a7a.

**Comment by jarun** [comment]
Thank you! Did you add the `risky` tag too? Maybe:

Similarly, if you want to install from git master (*risky*), run:

> Squashing unrelated commits makes bisecting a lot harder.

**Comment by jarun** [comment]
> Squashing unrelated commits makes bisecting a lot harder.

Yes I changed the setting back for `googler` now because you and me are the regular pushers here. I took a squash strategy for `Buku` because I get a number of PRs nowadays which do one thing in 5/6 commits.

**Comment by zmwangx** [comment]
> Did you add the risky tag too?

Done.

> I get a number of PRs nowadays which do one thing in 5/6 commits.

Yeah it's annoying when people don't rebase when they should.

**Pull request merged**
