### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TonyStark**
Installation instruction in Android

### CODE REVIEW

**Comment by zmwangx** [comment]
I'd say no to this. I've never seen a comparable project with a README that includes installation instructions for Android, or HP-UX, or Solaris, or whatever. Also, it would be weird for us to endorse a specific terminal emulator from Play Store, out of all places.

**Comment by jarun** [comment]
Oh come on! This is from Tony Stark, the Iron Man himself!

Jokes apart, your argument makes sense. So I'll save it in a gist or somewhere.

**Comment by kenorb** [comment]
You can add as a Wiki page.

**Comment by jarun** [comment]
> You can add as a Wiki page.

That's a good idea. I'll add it.

**Comment by jarun** [comment]
Added here - https://github.com/jarun/googler/wiki/Unofficial-guide-to-Android-installation

Thank you!

**Pull request closed without merging**
