### PR TITLE
Fix #114: disable user-agent and resurrect interface

### LINKED ISSUE #114: Issues with results if user-agent is removed
1. Google News doesn't work
2. A regular `hello` search results:
```
$ ./googler hello

1 HELLO! Online: celebrity & royal news, magazine, babies, weddings ...
/url?q=http://www.hellomagazine.com/&sa=U&ved=0ahUKEwjQw7PF3Z_NAhUQSI8KHfVNDTMQFghoMAw&usg=AFQjCNHe-OhTvjOvC5smGVTvd1mxsfl2FA
HELLO! Online brings you the latest celebrity & royal news from the UK & around  the world, magazine exclusives,
celeb babies, weddings, pregnancies and ...

2 hello network
/url?q=https://hello.com/&sa=U&ved=0ahUKEwjQw7PF3Z_NAhUQSI8KHfVNDTMQFghuMA0&usg=AFQjCNHu3ySM5MQ_ySXDktfr8Ax4fFxy4w
hello connects you with people and content around your passions. Show the  world who you are, express what you
love, and create meaningful connections.

3 Hello (Adele song) - Wikipedia, the free encyclopedia
/url?q=https://en.wikipedia.org/wiki/Hello_(Adele_song)&sa=U&ved=0ahUKEwjQw7PF3Z_NAhUQSI8KHfVNDTMQFgh0MA4&usg=AFQjCNHJRKExeuRwwdFmAKkJ6dH7qv_TeQ
"Hello" is a song by English singer Adele. It was released on 23 October 2015 by  XL Recordings as the lead
single from her third studio album, 25 (2015). Adele ...

4 Hello - Wikipedia, the free encyclopedia
/url?q=https://en.wikipedia.org/wiki/Hello&sa=U&ved=0ahUKEwjQw7PF3Z_NAhUQSI8KHfVNDTMQFgh6MA8&usg=AFQjCNEPQPRz_g4ms5UWaM9OQrZ8-qWzew
Hello is a salutation or greeting in the English language. It is first attested in  writing from 1833. Contents.
[hide]. 1 First use; 2 Etymology. 2.1 Telephone; 2.2 ...

5 Images for hello
/search?q=hello&ie=UTF-8&oe=UTF-8&prmd=ivnsfdm&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjQw7PF3Z_NAhUQSI8KHfVNDTMQsAQIgAE

6 HELLO! - Facebook
/url?q=https://www.facebook.com/hello/&sa=U&ved=0ahUKEwjQw7PF3Z_NAhUQSI8KHfVNDTMQFgiMATAV&usg=AFQjCNFX6GnLlw8l4pE7PM-eVFUijQimIg
HELLO! 1794375 likes · 54963 talking about this. The official Facebook page for  HELLO! magazine &
http://www.hellomagazine.com/ FOLLOW US @...

7 ADELE LYRICS - Hello - A-Z Lyrics
/url?q=http://www.azlyrics.com/lyrics/adele/hello.html&sa=U&ved=0ahUKEwjQw7PF3Z_NAhUQSI8KHfVNDTMQFgiSATAW&usg=AFQjCNHGIyMSO2JIfxsiYutLKdH21BVmvw
Hello, it's me. I was wondering if after all these years you'd like to meet. To go  over everything. They say
that time's supposed to heal ya. But I ain't done much ...

8 Hello
/url?q=https://hello.is/&sa=U&ved=0ahUKEwjQw7PF3Z_NAhUQSI8KHfVNDTMQFgiXATAX&usg=AFQjCNGwdUWTtCdsDuH8FLfNW3oDxaTyqQ
Sense by Hello wakes you up feeling great, improves your sleep, and helps you  learn how the environment of your
bedroom affects your rest.

9 Hello — Caller ID & Blocking - Android Apps on Google Play
/url?q=https://play.google.com/store/apps/details%3Fid%3Dcom.facebook.phone%26hl%3Den&sa=U&ved=0ahUKEwjQw7PF3Z_NAhUQSI8KHfVNDTMQFgidATAY&usg=AFQjCNHcLO9dQ-fNU0fT-KM6O5TW50jggA
Make your phone smarter with Hello. Built by Messenger just for Android, Hello  combines info from Facebook with
the contact info on your phone so it's easy to ...
```

a. URLs are malformed
b. multiple spaces in results: `Show the  world`, `around  the world`, `To go  over`
c. `Images for hello` show in results

### PR DESCRIPTION
**Pull request by jarun**
I will still consider this as experimental and not sure if it makes it to the next release. However the performance gains are considerable when user agent is disabled in the code. The network data transfer takes most of the time and this change impacts all of them. The profiling results below speak for themselves.

**With UA disabled and redirection**
```
$ python3 -m cProfile -s time ./googler hello --noprompt
...
         92398 function calls (91035 primitive calls) in 1.194 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       23    0.543    0.024    0.543    0.024 {method 'read' of '_ssl._SSLSocket' objects}
        2    0.214    0.107    0.214    0.107 {method 'do_handshake' of '_ssl._SSLSocket' objects}
        2    0.148    0.074    0.150    0.075 {built-in method _socket.getaddrinfo}
        2    0.085    0.043    0.085    0.043 {method 'connect' of '_socket.socket' objects}
        3    0.023    0.008    0.023    0.008 {built-in method _imp.create_dynamic}
        4    0.019    0.005    0.019    0.005 {built-in method builtins.compile}
     4730    0.012    0.000    0.012    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
      638    0.012    0.000    0.041    0.000 parser.py:301(parse_starttag)
        1    0.008    0.008    0.069    0.069 parser.py:134(goahead)
       48    0.007    0.000    0.007    0.000 {built-in method marshal.loads}
      638    0.006    0.000    0.012    0.000 googler:729(handler)
     62/1    0.005    0.000    1.195    1.195 {built-in method builtins.exec}
```

**With UA disabled, no redirection**
```
$ python3 -m cProfile -s time ./googler hello -c in --noprompt
...
         88228 function calls (86860 primitive calls) in 0.896 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       22    0.469    0.021    0.469    0.021 {method 'read' of '_ssl._SSLSocket' objects}
        1    0.103    0.103    0.103    0.103 {method 'do_handshake' of '_ssl._SSLSocket' objects}
        1    0.075    0.075    0.076    0.076 {built-in method _socket.getaddrinfo}
        1    0.042    0.042    0.042    0.042 {method 'connect' of '_socket.socket' objects}
        3    0.024    0.008    0.024    0.008 {built-in method _imp.create_dynamic}
        4    0.021    0.005    0.021    0.005 {built-in method builtins.compile}
     4717    0.013    0.000    0.013    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
      638    0.012    0.000    0.040    0.000 parser.py:301(parse_starttag)
        1    0.008    0.008    0.069    0.069 parser.py:134(goahead)
       48    0.007    0.000    0.007    0.000 {built-in method marshal.loads}
      638    0.005    0.000    0.009    0.000 googler:729(handler)
  232/230    0.005    0.000    0.013    0.000 {built-in method builtins.__build_class__}
```

**With UA enabled and redirection**
```
$ python3 -m cProfile -s time /usr/local/bin/googler hello --noprompt
...
         119405 function calls (118042 primitive calls) in 1.516 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      107    0.761    0.007    0.761    0.007 {method 'read' of '_ssl._SSLSocket' objects}
        2    0.232    0.116    0.232    0.116 {method 'do_handshake' of '_ssl._SSLSocket' objects}
        2    0.164    0.082    0.166    0.083 {built-in method _socket.getaddrinfo}
        2    0.079    0.039    0.079    0.039 {method 'connect' of '_socket.socket' objects}
        3    0.025    0.008    0.025    0.008 {built-in method _imp.create_dynamic}
        4    0.022    0.006    0.022    0.006 {built-in method builtins.compile}
     8101    0.022    0.000    0.022    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
     1009    0.020    0.000    0.067    0.000 parser.py:301(parse_starttag)
        1    0.013    0.013    0.118    0.118 parser.py:134(goahead)
     1080    0.010    0.000    0.010    0.000 {method 'search' of '_sre.SRE_Pattern' objects}
     1009    0.010    0.000    0.018    0.000 googler:729(handler)
       48    0.007    0.000    0.007    0.000 {built-in method marshal.loads}
      977    0.006    0.000    0.013    0.000 parser.py:386(parse_endtag)
  232/230    0.005    0.000    0.014    0.000 {built-in method builtins.__build_class__}
       48    0.005    0.000    0.005    0.000 {method 'decompress' of 'zlib.Decompress' objects}
     4094    0.005    0.000    0.008    0.000 _markupbase.py:48(updatepos)
     62/1    0.005    0.000    1.516    1.516 {built-in method builtins.exec}
```

**With UA enabled, no redirection**
```
$ python3 -m cProfile -s time /usr/local/bin/googler -c in hello --noprompt
...
         115558 function calls (114190 primitive calls) in 1.262 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      104    0.766    0.007    0.766    0.007 {method 'read' of '_ssl._SSLSocket' objects}
        1    0.106    0.106    0.106    0.106 {method 'do_handshake' of '_ssl._SSLSocket' objects}
        1    0.082    0.082    0.084    0.084 {built-in method _socket.getaddrinfo}
        1    0.039    0.039    0.039    0.039 {method 'connect' of '_socket.socket' objects}
        3    0.026    0.009    0.026    0.009 {built-in method _imp.create_dynamic}
        4    0.023    0.006    0.023    0.006 {built-in method builtins.compile}
     8120    0.021    0.000    0.021    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
     1012    0.020    0.000    0.062    0.000 parser.py:301(parse_starttag)
        1    0.012    0.012    0.111    0.111 parser.py:134(goahead)
     1077    0.010    0.000    0.010    0.000 {method 'search' of '_sre.SRE_Pattern' objects}
     1012    0.008    0.000    0.014    0.000 googler:729(handler)
       48    0.007    0.000    0.007    0.000 {built-in method marshal.loads}
      980    0.006    0.000    0.013    0.000 parser.py:386(parse_endtag)
  232/230    0.005    0.000    0.014    0.000 {built-in method builtins.__build_class__}
     4106    0.005    0.000    0.008    0.000 _markupbase.py:48(updatepos)
     62/1    0.005    0.000    1.263    1.263 {built-in method builtins.exec}
```

### CODE REVIEW

**Comment by jarun** [comment]
@shaggytwodope would it be possible for you to spare some time and test this change? It's a critical one and I need a second eye from some location other than India. It would be great if you can cover some of the base features.

I would completely understand if you are busy.

**Comment by shaggytwodope** [comment]
@jarun Omitted the full output, if you want me to run again I will and post it. However it's very large (may be best I post on gist or something). 

With UA disabled and redirection

`
107589 function calls (106149 primitive calls) in 0.622 seconds
`


With UA disabled, no redirection

`
102455 function calls (101010 primitive calls) in 0.696 seconds
`

With UA enabled and redirection

`
129344 function calls (127904 primitive calls) in 0.743 seconds
`

With UA enabled, no redirection

`
125530 function calls (124085 primitive calls) in 0.835 seconds
`

**Comment by jarun** [comment]
Thank you! It seems the performance improved. Are the search results looking fine?

**Comment by shaggytwodope** [comment]
Indeed the results are fine. Tho I cringe with Adele being a result lol. If you'd like any sort of testing on my end just ask. Excuse the delay.

**Comment by jarun** [comment]
Thanks! I'll test this one (probably) tonight and send you (hopefully) a smaller subset.

**Comment by jarun** [comment]
Note: the following query doesn't return any results:

`googler 3 HOURS The Best Relaxing Piano Flute Music Ever youtube`

The following change:
```
@@ -1085,7 +1085,7 @@ class GoogleParser(html.parser.HTMLParser):
             self.set_handlers_to('abstract')
             return 'abstract'
 
-        if not self.sitelinks and not self.news and tag == 'table':
+        if not self.sitelinks and not self.news and tag == 'table'  and 'ts' not in self.classes(attrs):
             self.set_handlers_to('sitelink_table')
             return 'sitelink_table'
```
seems to show the title and URL but no the abstract. Example data received:
```
<div class="g">
                                            <table class="ts">
                                                <tr>
                                                    <td colspan="2">
                                                        <h3 class="r"><a href="/url?q=https://www.youtube.com/watch%3Fv%3Don9OR3kRGLs&amp;sa=U&amp;ved=0ahUKEwiN5Z2466_NAhUFt48KHaeaDBwQtwIIHTAB&amp;usg=AFQjCNHE6UTA1yJQYNVSdSJA7Lw7v8SnYQ"><b>3 Hours</b> of <b>Relaxing Piano</b>, Cello &amp; <b>Flute Music</b> | Beautiful ... - <b>YouTube</b></a></h3>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td valign="top" width="1" style="padding:4px 8px 0 0">
                                                        <div class="th" style="position:relative;overflow:hidden;width:116px;height:65px">
                                                            <a href="/url?q=https://www.youtube.com/watch%3Fv%3Don9OR3kRGLs&amp;sa=U&amp;ved=0ahUKEwiN5Z2466_NAhUFt48KHaeaDBwQuAIIHjABUAE&amp;usg=AFQjCNHE6UTA1yJQYNVSdSJA7Lw7v8SnYQ">
                                                                <div style="margin-top:-11px"><img src="https://img.youtube.com/vi/on9OR3kRGLs/default.jpg?h=90&amp;w=120&amp;sigh=__bmucG2rntkuVnQ4Hg9cIqlESeyg=" width="116" alt="Video for 3 HOURS The Best Relaxing Piano Flute Music Ever youtube" align="middle">
                                                                </div>
                                                                <div style="position:absolute;bottom:0;right:0;font-size:11px;color:#fff;background-color:#222;padding:1px 3px;text-decoration:none;font-weight:bold;text-align:right">&#9658; 188:06</div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                    <td valign="top" style="padding-top:1px"><cite class="kv">https://www.<b>youtube</b>.com/watch?v=on9OR3kRGLs</cite><span class="st"><span class="f"><span class="nobr">1 Sep 2015</span> - <span class="nobr">188 min</span> - <span class="nobr">Uploaded by Peder B. Helland - Composer</span></span>
                                                        <br><b>Relaxing music</b> featuring <b>piano</b>, <b>flute</b> and cello, called &quot;Ocean Whisper&quot; ... 6 <b>Hours The</b> <b>...</b>
                                                        </span>
                                                    </td>
                                                </tr>
                                            </table>
                                        </div>
                                        <div class="g">
                                            <table class="ts">
                                                <tr>
                                                    <td colspan="2">
                                                        <h3 class="r"><a href="/url?q=https://www.youtube.com/watch%3Fv%3DWwv1hctniUY&amp;sa=U&amp;ved=0ahUKEwiN5Z2466_NAhUFt48KHaeaDBwQtwIIITAC&amp;usg=AFQjCNGU0vZ4NBu1rRsdSvUYR3dmYd8rBw"><b>3 HOURS Best Relaxing Music</b> &#39;Romantic <b>Piano</b> ... - <b>YouTube</b></a></h3>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td valign="top" width="1" style="padding:4px 8px 0 0">
                                                        <div class="th" style="position:relative;overflow:hidden;width:116px;height:65px">
                                                            <a href="/url?q=https://www.youtube.com/watch%3Fv%3DWwv1hctniUY&amp;sa=U&amp;ved=0ahUKEwiN5Z2466_NAhUFt48KHaeaDBwQuAIIIjACUAE&amp;usg=AFQjCNGU0vZ4NBu1rRsdSvUYR3dmYd8rBw">
                                                                <div style="margin-top:-11px"><img src="https://img.youtube.com/vi/Wwv1hctniUY/default.jpg?h=90&amp;w=120&amp;sigh=__zY8fbWUOVObuaEwZXJv4LMJYDdw=" width="116" alt="Video for 3 HOURS The Best Relaxing Piano Flute Music Ever youtube" align="middle">
                                                                </div>
                                                                <div style="position:absolute;bottom:0;right:0;font-size:11px;color:#fff;background-color:#222;padding:1px 3px;text-decoration:none;font-weight:bold;text-align:right">&#9658; 179:26</div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                    <td valign="top" style="padding-top:1px"><cite class="kv">https://www.<b>youtube</b>.com/watch?v=Wwv1hctniUY</cite><span class="st"><span class="f"><span class="nobr">10 Jun 2014</span> - <span class="nobr">179 min</span> - <span class="nobr">Uploaded by Meditation Relax Music</span></span>
                                                        <br><b>3 HOURS Best Relaxing Music</b> &#39;Romantic <b>Piano</b>&quot; Background <b>Music</b> for Stress ... 3:03 <b>...</b>
                                                        </span>
                                                    </td>
                                                </tr>
                                            </table>
                                        </div>
```

**Comment by jarun** [comment]
Next related commit at https://github.com/jarun/googler/commit/f90fe9852b8125824365489d6a1b3066041d2562.

**Comment by jarun** [comment]
https://github.com/jarun/googler/commit/5c1f359e1ec439a2bb07bf8c030e81fc6df19ec2 fixes #177. The previous auto-ref is incorrect.

**Pull request merged**
