### PR TITLE
googler.1: Simplify the SYNOPSIS section

### PR DESCRIPTION
**Pull request by zmwangx**
No one ever remembers to update the synopsis, so it's already horribly outdated. Moreover, without an auto generator, listing and formatting all the options is a pain in the ass. Just leave options to the `OPTIONS` section.

### CODE REVIEW

**Comment by jarun** [comment]
Thank you! We also need to add debian to the readme installation section. :)

**Comment by zmwangx** [comment]
We can say a word about googler available in sid, but I'm no Debian fan so I'm not sure how to install sid packages on a stable channel (except the `debootstrap` approach which I do know, but that's installing one distro on top of another). There's http://serverfault.com/q/22414 but I don't bother to try those myself.

**Comment by zmwangx** [comment]
I also have concerns about the package in its current form which I don't have time to elaborate on right now. I'll talk to you about that tomorrow on a private channel.

**Comment by jarun** [comment]
sure!

**Comment by jarun** [comment]
I added that.

**Pull request merged**
