### PR TITLE
Logo!

### PR DESCRIPTION
**Pull request by zmwangx**
I woke up in a good mood, and made a logo for googler!

googler logo

Here's the Sketch design file: <https://static.zhimingwang.org/20170818-googler.sketch>.

## Design

I created the logo in [Sketch](https://www.sketchapp.com/). It's top-notch, but it isn't available on Linux, and may not even be available to myself in a week (I am running a trial version of this $99 app). Therefore, below I'll detail most design decisions.

Note that the basic idea of the design — googler on a command prompt in a terminal window — is simple, and not very creative. This idea has been used by [Oh My Zsh](http://ohmyz.sh/), and probably other projects that I either can't think of at the moment or haven't come across. However, it fits the theme of googler — a Google CLI — perfectly.

### Canvas

- 512x192px transparent canvas.
- 6px margins all around, reducing the content area to 500x180px.

### Title bar

The title bar mimics a standard app title bar on macOS Sierra.

- 500x23px, with rounded corners of 5px radius and 1px inner border.
- Buttons with 12px diameter, 8px apart.
- Background color: `#f6f6f6`; border color: `#cccccc`; button colors:
  - Red: `#fc625d`;
  - Yellow: `#fec041`;
  - Green: `#35ce48`.

### Main window area

- 500x157px, with rounded corners of 5px radius and no border.
- Background color: Solarized base03 `#002b36`.

### Text

The text reads `$ googler▐`. The last character is U+3590 RIGHT HALF BLOCK, standing for a cursor.

- All characters except the last are rendered in [Courier Prime](https://quoteunquoteapps.com/courierprime/) ([SIL OFL](http://scripts.sil.org/OFL)), at 80pt (except the space, which is reduced to roughly match the spacing between "r" and "▐" in an attempt to center "googler").
- "▐" is rendered in [Source Code Pro](http://adobe-fonts.github.io/source-code-pro/) ([SIL OFL](http://scripts.sil.org/OFL)) at 66pt since it is not included in Courier Prime.
- Color of the "google" characters match those of [the official Google logo](https://web.archive.org/web/20170817185207if_/https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png). The six letters are colored blue, red, yellow, blue, green, and red, respectively; the hex values of the colors are:
  - Blue: `#4285f4`;
  - Red: `#ea4335`;
  - Yellow: `#fbbc05`;
  - Green: `#34a853`.
- The color of the remaining characters: Solarized base1 `#93a1a1`.

### CODE REVIEW

**Comment by shaggytwodope** [comment]
I love it. Good choice for background color.

**Comment by zmwangx** [comment]
@shaggytwodope Thanks! 😯

**Comment by zmwangx** [comment]
By the way, and here's another version where the characters are not converted to outline — you'll need Courier Prime and Source Code Pro to render it properly. It shouldn't be used in production, but it is closer to the source (and not minified), so to speak.

**Comment by jarun** [comment]
Simply awesome! :+1:

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
Can we have it without the top bar?

**Comment by zmwangx** [comment]
@jarun I understand your sentiment that the nuances of the title bar may be too elaborate for a logo. I originally put it there to complete the terminal window, which provides a natural boundary to the logo — the window chrome; without it, we have a dark blob that abruptly ends at some random rectangular boundary, as depicted in the following mockup, and that, IMO, looks bad on any background with a different color. (See also: Mozilla's new logo.)



Now that I think about it though, maybe the terminal window is superfluous. What if we embrace simplicity by discarding the background altogether? I present a new logo that's just `$ googler▐` and no more:



This one is 512x128px, with the cursor and spacing around "googler" reworked. The cursor is now a rectangle that's precisely the height of "$" and half the width. The spacing is debatable.

**Comment by jarun** [comment]
> random rectangular boundary

It did occur to me. I thought there might be some easy way to round it off.

BUT,

Yes, the image without BG is what we should have! Please do a force push so the prev image is overwritten from history.

**Comment by jarun** [comment]
@zmwangx I woke up to this today - http://www.omgubuntu.co.uk/2017/08/search-google-from-the-command-line.

@shaggytwodope shared with me. So here's for your morning as well. ;)

**Pull request merged**
