### PR TITLE
Introduce a protocol for Google-breaks-everything incidents

### PR DESCRIPTION
**Pull request by zmwangx**
There have been enough Google-breaks-everything shitstorms, it's time to introduce a better protocol to reduce user confusion during these trying periods.

Here's the protocol:

- Once a report is confirmed and proven to be non-transient (e.g. still reproducible after 24 hours), regardlessly of whether a fix can be made available immediately, the epoch in `googler` and `info.json` should be advanced to the date of the report (in UTC), and the issue number recorded. `info.json` should look like:

  ```json
  {
      "epoch": "20201001",
      "tracking_issue": 372,
      "fixed_on_master": false,
      "fixed_in_release": false
  }
  ```

  At this point users would see a message like this:

  ```console
  $ googler hello  # Issue acknowledged, not fixed.
  No results.
  Your version of googler is broken due to Google-side changes.
  The issue is tracked at https://github.com/jarun/googler/issues/372.
  ```

- Once a fix is committed to master, `fixed_on_master` should be set to `true`:

  ```json
  {
      "epoch": "20201001",
      "tracking_issue": 372,
      "fixed_on_master": true,
      "fixed_in_release": false
  }
  ```

  At this point users would see a message like this:

  ```console
  $ googler hello  # Fixed on master, not released.
  No results.
  Your version of googler is broken due to Google-side changes.
  The fix has been pushed to master, pending a release.
  Please download the master version https://git.io/googler or wait for a release.
  ```

- Once the fix is released, `fixed_in_released` should be updated to the version tag:

  ```json
  {
      "epoch": "20201001",
      "tracking_issue": 372,
      "fixed_on_master": true,
      "fixed_in_release": "v4.3"
  }
  ```

  At this point users would see a message like this:

  ```console
  $ googler hello  # Fix released.
  No results.
  Your version of googler is broken due to Google-side changes.
  A new version, v4.3, has been released to address the changes.
  Please upgrade to the latest version.
  ```

I'll create a wiki page for this protocol if we can agree on it.

### CODE REVIEW

**Comment by jarun** [comment]
I'm good with this. We should add the link well-highlighted in the new defect template as well.

**Comment by jarun** [comment]
Thank you!

**Comment by zmwangx** [comment]
> We should add the link well-highlighted in the new defect template as well.

Sorry, which link?

**Comment by jarun** [comment]
> I'll create a wiki page for this protocol if we can agree on it.

To this Wiki page.

**Comment by zmwangx** [comment]
Added https://github.com/jarun/googler/wiki/The-Google-Breaks-Everything-Protocol (sorry for the delay).

The page is for developers (i.e. us) though. There already a user-oriented page (https://github.com/jarun/googler/wiki/What-to-do-when-you-encounter-%22No-results%22) which is linked in the warning message, probably to limited effect.

I do think we should raise the barrier of opening a new issue. I believe GitHub has introduced tools to achieve that to some extent. I’ll look into it later.

**Pull request merged**
