### PR TITLE
Miscellaneous improvements

### PR DESCRIPTION
**Pull request by zmwangx**
- Add -V, --version option (standard stuff);
- Reorder options in completion defs according to help text, so that checking whether any option's missing is easier;
- Add Debian and Ubuntu availability badges (can't give a version, so just point out which distro releases googler is available on, and link to respective package search pages).

We may want to cut a release some time soon.

### CODE REVIEW

**Comment by jarun** [comment]
> We may want to cut a release some time soon.

How about late today? ;)

**Comment by zmwangx** [comment]
> How about late today? ;)

No problem.

**Comment by jarun** [comment]
:+1:

**Comment by jarun** [comment]
Thank you!

**Pull request merged**
