### PR TITLE
I quit

### PR DESCRIPTION
**Pull request by zmwangx**
Remove my name from the project. I quit.

Normally I would explain thoroughly, but I'm too tired to explain now, so I'll just be a jerk and quit without a satisfactory explanation, except for briefly pointing out that

- I don't want to put my name under this piece of software anymore (license is a factor but not the only one); 
- I'm getting tired; 
- This was not planned; kind of mood driven, but I won't regret it.

I won't even contribute fixes anymore (in the parts that I wrote), which I promised earlier. Please feel free to remove my collaborator privilege, or not.

### CODE REVIEW

**Comment by jarun** [comment]
3 things:

- I mentioned that I'll re-look at it.
- I was doing things in a hurry because I've to leave and I wanted to make a release for you. I know it's late there.

I think there's a miscommunication here if you think I'm not paying heed to your suggestions. Anyway, I'll make the release in the afternoon in a calm head and with the changes done the proper way.

**Comment by zmwangx** [comment]
> I mentioned that I'll re-look at it.

That's not a factor.

> I was doing things in a hurry because I've to leave and I wanted to make a release for you.

Again, that's not a factor.

> if you think I'm not paying heed to your suggestions. 

That's not the case.

> mood driven

All factors are things that happened **before** #115, which I won't explain in detail.

**Comment by zmwangx** [comment]
Actually, please just think of this as

- I'm busy with other (new) things in life so I don't have time for this;
- I've lost interest.

both of which are factors.

**Comment by jarun** [comment]
Understood! All the best! :+1: 

Thanks a lot for you contributions. You'll remain a collaborator as I don't see a reason from my side to remove it. And you're welcome back when you have a change of heart.

**Comment by zmwangx** [comment]
I do wish to remove my name though.

**Pull request closed without merging**
