### PR TITLE
Fix parser

### LINKED ISSUE #372: Stopped working?
- Output of `googler -d`:

 ```
[DEBUG] googler version 4.2
[DEBUG] Python version 3.7.4
[DEBUG] Platform: Darwin-15.6.0-x86_64-i386-64bit
[DEBUG] Connecting to new host www.google.com
[DEBUG] Opened socket to 216.58.215.68:443
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=test&sei=YhfWbCYXQL2KPfSS1sfGbA
[DEBUG] Cookie: CGIC=Igl0ZXh0L2h0bWw
[DEBUG] Response body written to '/var/folders/fm/flpqjgss1mz5hhs92sj_6fm40000gn/T/googler-response-h3lbic2q.html'.
No results.
If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.
```

- Link to the response body:

https://gist.github.com/097115/821c10653b18cc83d333329ab8371e9c

- Details of operating system, Python version used:

Both Ubuntu and macOS, both python 3.5.2 and 3.7.4. Worked just a few hours ago, and now suddenly returns no results (both 4.2 and the latest master).

### PR DESCRIPTION
**Pull request by zmwangx**
Fixes #372, hopefully.

Old parser is kept just in case the new structure isn't served to every domain / every UA / every user.

Parser now capable of parsing multiple metadata fields too, e.g. "Released", "Genre", etc. for songs. Wikipedia search results often have these metadata fields, it seems. I have chosen ` | ` as the delimiter in our single-line output, which is of course debatable.

Example:

```console
$ googler linux

 1.  Linux.org
     https://www.linux.org/
     Sep 16, 2020
     Friendly Linux Forum.

 2.  Linux - Wikipedia
     https://en.wikipedia.org/wiki/Linux
     Source model: Open source | Userland: GNU | Initial release: September 17, 1991; 29 years a... | OS family: Unix-like
     Linux is a family of open source Unix-like operating systems based on the Linux kernel, an operating system kernel first released on September 17,
     1991, by ...

 3.  The Linux Foundation – Supporting Open Source Ecosystems
     https://www.linuxfoundation.org/
     Developer: Linus Torvalds
     The Linux Foundation supports the creation of sustainable open source projects and ecosystems in blockchain, deep learning, networking, and more.

...
```

```console
$ googler never gonna give you up

 1.  Never Gonna Give You Up - YouTube
     https://www.youtube.com/watch?v=dGeEuyG_DIc
     Mar 10, 2020, Uploaded by Carlos Marín, Topic
     Never Gonna Give You Up · Rick Astley Whenever You Need Somebody ℗ 1987 Sony Music Entertainment UK ...

 2.  Rick Astley - Never Gonna Give You Up (The Roxy 1987 ...
     https://www.youtube.com/watch?v=IO9XlQrEt2Y
     Jul 6, 2016, Uploaded by RickAstleyVEVO
     Never Gonna Give You Up” by Rick Astley, performed live at The Roxy, 1987 Listen to Rick Astley: https ...

 3.  The Story of the Best Meme EVER: "Never Gonna Give You Up"
     https://www.youtube.com/watch?v=QMW4AqbuSGg
     Jun 19, 2020, Uploaded by Alfo Media
     Never Gonna Give You Up / Rickrolling / Rickroll / Rick Astley / Live / Music Video / Review / Reaction / Video ...

 4.  Rick Astley - Never Gonna Give You Up [HQ] - YouTube
     https://www.youtube.com/watch?v=DLzxrzFCyOs
     Apr 11, 2015, Uploaded by AllKindsOfStuff
     Artist: Rick Astley Title: Never Gonna Give You Up Difference with original: nothing but the quality of audio and ...

 5.  Never Gonna Give You Up - Wikipedia
     https://en.wikipedia.org/wiki/Never_Gonna_Give_You_Up
     Released: 27 July 1987 | Producer(s): Stock Aitken Waterman | Genre: Dance-pop; blue-eyed soul; | Songwriter(s): Stock Aitken Waterman
     "Never Gonna Give You Up" is a song recorded by British singer and songwriter Rick Astley, released as his debut single on 27 July 1987. It was written
     and ...

...
```

### CODE REVIEW

**Comment by jarun** [comment]
Thanks a lot! Can you also fix the failing test cases?

**Comment by zmwangx** [comment]
Looking into it at the moment.

**Comment by jarun** [comment]
Also, with this fix in place, I don't see the abstract for 1 search result:

```
$ g hello world    

 1.  "Hello, World!" program - Wikipedia [en.wikipedia.org]
     History · Variations · Time to Hello World
     A "Hello, World!" program generally is a computer program that outputs or displays the message
     "Hello, World!". Such a program is very simple in most ...

 2.  Hello, World! - Learn Python - Free Interactive Python Tutorial [www.learnpython.org]
     Hello, World! Python is a very simple language, and has a very straightforward syntax. It encourages
     programmers to program without boilerplate (prepared) ...

 3.  Hello World · GitHub Guides [guides.github.com]
     Jul 24, 2020
     You'll create your own Hello World repository and learn GitHub's Pull Request workflow, a popular
     way to create and review code. No coding ...

 4.  Hello World! - Manning [www.manning.com]
     Hello World! Computer Programming for Kids and Other Beginners. Warren D. Sande and Carter Sande.
     March 2009; ISBN 9781933988498; 432 pages.

 5.  Hello World! Second Edition - Manning [www.manning.com]

 6.  HelloWorld Coliving, Student Hostels & Coworking Spaces [thehelloworld.com]
     Hello World provides coliving, student housing, coworking, social spaces and natural habitats to
     those exploring the evolution of humanity through positive ...

 7.  Hello World – React [reactjs.org]
     The smallest React example looks like this: ReactDOM.render( <h1>Hello, world!</h1>,
     document.getElementById('root') );. It displays a heading saying “Hello, ...
```

I can see it in the web search results:



Is this expected?

**Comment by jarun** [comment]
Attaching the response.
[Uploading googler-response-opa9i3yo.zip…]()

**Comment by zmwangx** [comment]
The "Second Edition" result doesn't show up in my results for "hello world", and when I search for "hello world manning":

```
$ googler hello world manning

 1.  Hello World! Second Edition - Manning
     https://www.manning.com/books/hello-world-second-edition
     Rating: 4.7, 16 reviews
     This updated and revised edition of Hello World! introduces the world of computer programming in a clear and engaging style. Written by Warren Sande
     and his ...

 2.  Hello World! Third Edition - Manning
     https://www.manning.com/books/hello-world-third-edition
     Rating: 4.7, 6 reviews
     Hello World! Computer Programming for Kids and Other Beginners, Third Edition introduces the world of computer programming in a clear and fun style.
     Using ...

...
```

complete with ratings. Can you send me your HTML?

**Comment by zmwangx** [comment]
> Attaching the response.

Actually I think you submitted your comment before the upload was complete, so that link's invalid, empty href.

**Comment by jarun** [comment]
Now it shows correctly somehow! Leave it be! ;)

**Comment by zmwangx** [comment]
Might still want to take a look at that `googler-response-opa9i3yo`, if you still have it. Better fix it all now than have other issues pop up later.

**Comment by jarun** [comment]
That's true but I deleted the files thinking the upload was successful. However, after that all the queries work.

I'll keep trying and if I hit it I will upload. :+1:

**Comment by zmwangx** [comment]
Never mind then!

**Pull request merged**
