### PR TITLE
Fix the --news functionality

### PR DESCRIPTION
**Pull request by rfaile313**
Fixes https://github.com/jarun/googler/issues/415

Google changed the way its news results function around September 2021. 

Changing the parser inline breaks the non-news functionality, so setting 3 variables and passing them to the parser based on whether self.news is set or not works and seems like an easy way to do this.

Image of this patch applied and passing the `--news` flag:

https://i.imgur.com/7keZc4X.png

Image of this patch applied running googler normally:

https://i.imgur.com/IRJxmbV.png

### CODE REVIEW

**Comment by jarun** [comment]
CI fails, can you please check?

**Comment by rfaile313** [comment]
> CI fails, can you please check?

I looked, seems like the same portion that is failing on `main` and not related to my changes: https://github.com/jarun/googler/runs/3642882511

fwiw i tested on 3.6 and 3.9:

```
#python3 --version
Python 3.6.9
#googler business --news

 1.  Financial Times.Influencer marketing is no silver bullet for small business.Some companies strike gold with the strategy, but for most, it needs to be part of a mixed approach..8 hours ago
     https://www.ft.com/content/ce9422d3-6a35-484d-a777-160ae9919854
     Influencer marketing is no silver bullet for small business
     Financial Times

 2.  TechCrunch.Flippa raises $11M to match online asset and business buyers, sellers.Flippa uses a proprietary business valuation tool and algorithm to match online business owners to qualified buyers..22 hours ago
     https://techcrunch.com/2021/09/20/flippa-raises-11m-to-match-online-asset-and-business-buyers-sellers/
     Flippa raises $11M to match online asset and business buyers, sellers
     TechCrunch

 3.  USA Today.House Democrats' tax plan is a disaster. Here's how it would punish small businesses..Talk about awkward. As usual, the White House offered platitudes this month at the start of Small Business Week. Small businesses are the....2 hours ago
     https://www.usatoday.com/story/opinion/2021/09/21/democrats-tax-plan-punish-small-businesseses/8417990002/
     House Democrats' tax plan is a disaster. Here's how it would punish small businesses.
     USA Today
```

**Comment by jarun** [comment]
Also the subjects a too long. Can you see what went wrong?

```
$ news india

 1.  The Financial Express.Coronavirus (Covid-19) India Live News: India’s govt won’t buy Pfizer, Moderna vaccines amid local output, says sources.1 hour ago [www.financialexpress.com]
     India reports new cases of COVID-19

 2.  Times of India.India says UK govt's stand on Covishield 'discriminatory', warns of 'reciprocal action'.India News: According to new rules announced by the United Kingdom, Indian travellers who have received both doses of the Covishield vaccine....2 hours ago [timesofindia.indiatimes.com]
     India says UK govt's stand on Covishield 'discriminatory', warns of 'reciprocal action'
     Times of India

 3.  India Today.Viral fever grips children in India: What is it and how can kids be protected | An explainer.Viral fever cases are on the rise in parts of India. Here's an explainer on the fever and what can you do to protect your kids..1 hour ago [www.indiatoday.in]
     Viral fever grips children in India: What is it and how can kids be protected | An explainer
     India Today

 4.  The Indian Express.Amid Cong Punjab drama, Pilot meets Rahul, discusses ‘Rajasthan reshuffle’.The much-discussed reshuffle in the Ashok Gehlot government in Rajasthan has been hanging fire for some time, and the two leaders are learnt....13 hours ago [indianexpress.com]
     Amid Cong Punjab drama, Pilot meets Rahul, discusses ‘Rajasthan reshuffle’
     The Indian Express

googler (? for help) n

 1.  The Indian Express.Engaged with India on Covid-19 vaccine certification: UK.According to new rules, Indian travellers who have received both doses of the Covishield vaccine manufactured by the Serum Institute of India (....11 hours ago [indianexpress.com]
     Engaged with India on Covid-19 vaccine certification: UK
     The Indian Express

 2.  The Economic Times.Indian foreign minister Jaishankar urges UK to resolve COVID quarantine dispute.India's Covishield vaccine, developed by AstraZeneca and manufactured in India by Pune-based Serum Institute, is not recognised by Britain under....4 hours ago [economictimes.indiatimes.com]
     Indian foreign minister Jaishankar urges UK to resolve COVID quarantine dispute
     The Economic Times

 3.  The Economic Times.How India flipped its vaccine fortunes.The health ministry and SII did not immediately respond to a request for comment. Bharat Biotech, the producer of India's first domestically....4 hours ago [economictimes.indiatimes.com]
     How India flipped its vaccine fortunes
     The Economic Times

 4.  CNBC TV18.Coronavirus News LIVE Updates: India calls new UK COVID-19 vaccine rules 'discriminatory'.Coronavirus India News LIVE Updates: India added 26,115 new cases of coronavirus infection taking the total tally to 3,35,04,534,....1 hour ago [www.cnbctv18.com]
     Coronavirus News LIVE Updates: India calls new UK COVID-19 vaccine rules 'discriminatory'
     CNBC TV18

 5.  Hindustan Times.Could have immense positive impact: Gavi on India's move to export Covid-19 vax.Global vaccine alliance Gavi expressed its willingness to engage with the Indian government and Pune-based Serum Institute of India on Tuesday,....5 hours ago [www.hindustantimes.com]
     Could have immense positive impact: Gavi on India's move to export Covid-19 vax
     Hindustan Times

 6.  Al Jazeera.India’s aim to tighten e-com rules faces internal gov’t dissent.A handful of ministries, including the finance ministry, have raised concerns about the proposed rules calling them 'excessive'. Global....5 hours ago [www.aljazeera.com]
     India’s aim to tighten e-com rules faces internal gov’t dissent
     Al Jazeera

 7.  Times of India.CIA officer reports Havana syndrome symptoms on India trip: Reports.CIA officer reports Havana syndrome symptoms on India trip: Reports. Reuters / Updated: Sep 21, 2021, 15:00 IST. FacebookTwitterLinkedinEMail..7 hours ago [timesofindia.indiatimes.com]
     CIA officer reports Havana syndrome symptoms on India trip: Reports
     Times of India

googler (? for help

```

**Comment by rfaile313** [comment]
> Thanks for the PR.

Np thank you for the helpful communicaton

> See if you can fix the CI failures. I am just too far from python to look into these anymore.

Yeah I can look into the CI failures in general this weekend, I have some idea on why they occur.

> Also the subjects a too long. Can you see what went wrong?

Yes they are different with the news flag passed. It is tough because google removed the h3 tag 🙃 but probably not impossible. I will look this weekend. 

Thanks a lot!

**Comment by jarun** [comment]
@rfaile313 did you get the time to check the above?

**Pull request merged**
