### PR TITLE
Show "showing results for..."  alerts in --noprompt mode

### PR DESCRIPTION
**Pull request by zmwangx**
```console
$ ./googler --np -n 5 helol world
Showing results for hello world; use -x, --exact for an exact search.
 1.  "Hello, World!" program - Wikipedia
     https://en.wikipedia.org/wiki/%22Hello,_World!%22_program
     A "Hello, World!" program is a computer program that outputs or displays the message "Hello, World!". Because it is very simple in most programming
     languages, ...

 2.  HelloWorld, A Merkle Company
     https://www.helloworld.com/
     A powerful combination of native technology and marketing strategy allowing brands to create unforgettable interactions, drive consumer demand and ...

 3.  Hello, World! - Learn Java - Free Interactive Java Tutorial
     https://www.learnjavaonline.org/en/Hello%2C_World%21
     Hello, World! Java is an object oriented language (OOP). Objects in Java are called "classes". Let's go over the Hello world program, which simply
     prints "Hello, ...

 4.  Hello, World! - Learn Python - Free Interactive Python Tutorial
     https://www.learnpython.org/en/Hello,_World!
     Hello, World! Python is a very simple language, and has a very straightforward syntax. It encourages programmers to program without boilerplate
     (prepared) ...

 5.  hello world - YouTube
     https://www.youtube.com/watch?v=Yw6u6YkTgQ4
     Mar 30, 2018 - 2 min - Uploaded by Louie Zonga test of a virtual singer software - http://www.myriad-online.com/en/products/ virtualsinger.htm ...
```

### CODE REVIEW

**Comment by jarun** [comment]
Can we have:

    Showing results for hello world; use -x, --exact for an exact search.
aligned to "Hello world" in the first result and have a newline after?

**Comment by zmwangx** [comment]
> aligned

Alignment doesn't make much sense since this alert is displayed in prompt color, which is reverse video by default. The first character is nonempty anyway, so you won't see your alignment effect.

Now that you mention this, why do we waste the entire column?

> have a newline

I was going for compactness and had redirected stdin in mind, since the alerts are shown in JSON mode too. But if you insist.

**Comment by jarun** [comment]
At least the newline. ;)

**Comment by zmwangx** [comment]
Okay, added empty line prelude even in non-interactive mode.

**Comment by jarun** [comment]
Thank you! ;)

**Pull request merged**
