### PR TITLE
Testing overhaul

### PR DESCRIPTION
**Pull request by zmwangx**
Rewrite test suite based on survey of past issues and regressions.

Use pytest instead of homegrown "framework". Use structured output to simplify
programmatic testing.

Migrate to GitHub Actions.

### CODE REVIEW

**Comment by zmwangx** [comment]
Note: to properly investigate failures we sometimes might need to get our hands on the raw HTML response instead of truncated strings from pytest, so ideally we need to package up the raw HTML responses as artifact. This is already possible right now with --debug (to make things easier we can set a special TMPDIR, then zip up the whole thing at the end). However, I'm saving this work for later if the need actually arises.

**Comment by zmwangx** [comment]
And... the PR doesn't trigger GitHub Actions (guess it has to be in the branch first). Here's how the workflow turned out on my fork: https://github.com/zmwangx/googler/actions/runs/114040792

There should be zero setup other than merging.

**Comment by jarun** [comment]
CI is failing. Please take a look.

**Comment by zmwangx** [comment]
CircleCI is failing because I deleted CircleCI.

**Comment by jarun** [comment]
Cool! Is it possible to have a button for status in Readme.md?

**Comment by zmwangx** [comment]
Added badge.

**Comment by jarun** [comment]
Thank you!

**Comment by zmwangx** [comment]
Cool, passed on master. One more step: need to disable CircleCI, or it will keep reporting build status to GitHub, result in commits marked as failure, and send email 😃

**Comment by jarun** [comment]
Will do. Also how about auto-package generation on new release? Would that work or we need to add something?

**Comment by zmwangx** [comment]
Oh I forgot about that. I'll add it back after taking a shower.

**Comment by jarun** [comment]
Sure thing!

**Pull request merged**
