### PR TITLE
[issue template] minor typos

### PR DESCRIPTION
**Pull request by shaggytwodope**

### CODE REVIEW

**Comment by zmwangx** [comment]
Oops shame on me for not running aspell. Thanks.

**Comment by zmwangx** [comment]
I cherry picked your commit to avoid an unsigned merge commit. You're still the author, and will get full credit for that.

@jarun I merged this because it's trivial enough.

**Comment by jarun** [comment]
:+1:

**Comment by jarun** [comment]
If you use vim you can [integrate](https://tuxdiary.com/2014/10/04/enable-spellcheck-language-vim/) spell-check and automatic whitespace removal. This had been my problem too.

**Comment by zmwangx** [comment]
I use Emacs, and there are a million ways to spell check. Just don't have that habit...

**Comment by zmwangx** [comment]
Plus spell checking usually turn up tons of false negatives, due to the large number of technical speak.

**Comment by jarun** [comment]
> and there are a million ways to spell check

Sorry, I don't know all of them. I just shared my own experience. I guess it seems out of place or wrong or uncalled for suggestion. I would keep it in mind in future before posting such things.

**Comment by zmwangx** [comment]
> I guess it seems out of place or wrong or uncalled for suggestion.

Well, not at all... I said "there are a million ways to spell check" because there are indeed a lot of them: https://www.emacswiki.org/emacs/CategorySpelling. Just stating an exaggerated fact...

**Comment by shaggytwodope** [comment]
I can suggest a tool for both of you, codespell. It's not perfect but it catches a fair bit of things. Aside from spell checking within the editor (vim guy here) its a great tool just to double check. Being dyslexic it helps me a ton. https://github.com/lucasdemarchi/codespell

**Comment by zmwangx** [comment]
Cool, will take a look. In fact, in Emacs I use abbrev-mode in text-mode and its descendants (including markdown-mode) to autocorrect common typos (e.g. teh -> the) as I type. But apparently my tiny lexicon doesn't cover "developement"...

**Pull request closed without merging**
